#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQtoSQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FilmoviDB")]
	public partial class FilmoviDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFilm(Film instance);
    partial void UpdateFilm(Film instance);
    partial void DeleteFilm(Film instance);
    partial void InsertRecenzija(Recenzija instance);
    partial void UpdateRecenzija(Recenzija instance);
    partial void DeleteRecenzija(Recenzija instance);
    partial void InsertStatus(Status instance);
    partial void UpdateStatus(Status instance);
    partial void DeleteStatus(Status instance);
    partial void InsertZanr(Zanr instance);
    partial void UpdateZanr(Zanr instance);
    partial void DeleteZanr(Zanr instance);
    #endregion
		
		public FilmoviDBDataContext() : 
				base(global::LINQtoSQL.Properties.Settings.Default.FilmoviDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FilmoviDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FilmoviDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FilmoviDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FilmoviDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Film> Films
		{
			get
			{
				return this.GetTable<Film>();
			}
		}
		
		public System.Data.Linq.Table<Recenzija> Recenzijas
		{
			get
			{
				return this.GetTable<Recenzija>();
			}
		}
		
		public System.Data.Linq.Table<Status> Status
		{
			get
			{
				return this.GetTable<Status>();
			}
		}
		
		public System.Data.Linq.Table<Zanr> Zanrs
		{
			get
			{
				return this.GetTable<Zanr>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DodajFilm")]
		public int sp_DodajFilm([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Naziv", DbType="NVarChar(200)")] string naziv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DatumGledanja", DbType="Date")] System.Nullable<System.DateTime> datumGledanja, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdZanr", DbType="Int")] System.Nullable<int> idZanr, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdStatus", DbType="Int")] System.Nullable<int> idStatus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), naziv, datumGledanja, idZanr, idStatus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DodajZanr")]
		public int sp_DodajZanr([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NazivZanra", DbType="NVarChar(100)")] string nazivZanra)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nazivZanra);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Film")]
	public partial class Film : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdFilm;
		
		private string _Naziv;
		
		private System.DateTime _DatumGledanja;
		
		private int _IdZanr;
		
		private int _IdStatus;
		
		private EntitySet<Recenzija> _Recenzijas;
		
		private EntityRef<Status> _Status;
		
		private EntityRef<Zanr> _Zanr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdFilmChanging(int value);
    partial void OnIdFilmChanged();
    partial void OnNazivChanging(string value);
    partial void OnNazivChanged();
    partial void OnDatumGledanjaChanging(System.DateTime value);
    partial void OnDatumGledanjaChanged();
    partial void OnIdZanrChanging(int value);
    partial void OnIdZanrChanged();
    partial void OnIdStatusChanging(int value);
    partial void OnIdStatusChanged();
    #endregion
		
		public Film()
		{
			this._Recenzijas = new EntitySet<Recenzija>(new Action<Recenzija>(this.attach_Recenzijas), new Action<Recenzija>(this.detach_Recenzijas));
			this._Status = default(EntityRef<Status>);
			this._Zanr = default(EntityRef<Zanr>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFilm", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdFilm
		{
			get
			{
				return this._IdFilm;
			}
			set
			{
				if ((this._IdFilm != value))
				{
					this.OnIdFilmChanging(value);
					this.SendPropertyChanging();
					this._IdFilm = value;
					this.SendPropertyChanged("IdFilm");
					this.OnIdFilmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziv", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Naziv
		{
			get
			{
				return this._Naziv;
			}
			set
			{
				if ((this._Naziv != value))
				{
					this.OnNazivChanging(value);
					this.SendPropertyChanging();
					this._Naziv = value;
					this.SendPropertyChanged("Naziv");
					this.OnNazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumGledanja", DbType="Date NOT NULL")]
		public System.DateTime DatumGledanja
		{
			get
			{
				return this._DatumGledanja;
			}
			set
			{
				if ((this._DatumGledanja != value))
				{
					this.OnDatumGledanjaChanging(value);
					this.SendPropertyChanging();
					this._DatumGledanja = value;
					this.SendPropertyChanged("DatumGledanja");
					this.OnDatumGledanjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdZanr", DbType="Int NOT NULL")]
		public int IdZanr
		{
			get
			{
				return this._IdZanr;
			}
			set
			{
				if ((this._IdZanr != value))
				{
					if (this._Zanr.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdZanrChanging(value);
					this.SendPropertyChanging();
					this._IdZanr = value;
					this.SendPropertyChanged("IdZanr");
					this.OnIdZanrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdStatus", DbType="Int NOT NULL")]
		public int IdStatus
		{
			get
			{
				return this._IdStatus;
			}
			set
			{
				if ((this._IdStatus != value))
				{
					if (this._Status.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdStatusChanging(value);
					this.SendPropertyChanging();
					this._IdStatus = value;
					this.SendPropertyChanged("IdStatus");
					this.OnIdStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Film_Recenzija", Storage="_Recenzijas", ThisKey="IdFilm", OtherKey="IdFilm")]
		public EntitySet<Recenzija> Recenzijas
		{
			get
			{
				return this._Recenzijas;
			}
			set
			{
				this._Recenzijas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Status_Film", Storage="_Status", ThisKey="IdStatus", OtherKey="IdStatus", IsForeignKey=true)]
		public Status Status
		{
			get
			{
				return this._Status.Entity;
			}
			set
			{
				Status previousValue = this._Status.Entity;
				if (((previousValue != value) 
							|| (this._Status.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Status.Entity = null;
						previousValue.Films.Remove(this);
					}
					this._Status.Entity = value;
					if ((value != null))
					{
						value.Films.Add(this);
						this._IdStatus = value.IdStatus;
					}
					else
					{
						this._IdStatus = default(int);
					}
					this.SendPropertyChanged("Status");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Zanr_Film", Storage="_Zanr", ThisKey="IdZanr", OtherKey="IdZanr", IsForeignKey=true)]
		public Zanr Zanr
		{
			get
			{
				return this._Zanr.Entity;
			}
			set
			{
				Zanr previousValue = this._Zanr.Entity;
				if (((previousValue != value) 
							|| (this._Zanr.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Zanr.Entity = null;
						previousValue.Films.Remove(this);
					}
					this._Zanr.Entity = value;
					if ((value != null))
					{
						value.Films.Add(this);
						this._IdZanr = value.IdZanr;
					}
					else
					{
						this._IdZanr = default(int);
					}
					this.SendPropertyChanged("Zanr");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Recenzijas(Recenzija entity)
		{
			this.SendPropertyChanging();
			entity.Film = this;
		}
		
		private void detach_Recenzijas(Recenzija entity)
		{
			this.SendPropertyChanging();
			entity.Film = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recenzija")]
	public partial class Recenzija : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdRecenzije;
		
		private string _TekstRecenzije;
		
		private int _Ocena;
		
		private System.DateTime _DatumRecenzije;
		
		private int _IdFilm;
		
		private EntityRef<Film> _Film;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdRecenzijeChanging(int value);
    partial void OnIdRecenzijeChanged();
    partial void OnTekstRecenzijeChanging(string value);
    partial void OnTekstRecenzijeChanged();
    partial void OnOcenaChanging(int value);
    partial void OnOcenaChanged();
    partial void OnDatumRecenzijeChanging(System.DateTime value);
    partial void OnDatumRecenzijeChanged();
    partial void OnIdFilmChanging(int value);
    partial void OnIdFilmChanged();
    #endregion
		
		public Recenzija()
		{
			this._Film = default(EntityRef<Film>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRecenzije", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdRecenzije
		{
			get
			{
				return this._IdRecenzije;
			}
			set
			{
				if ((this._IdRecenzije != value))
				{
					this.OnIdRecenzijeChanging(value);
					this.SendPropertyChanging();
					this._IdRecenzije = value;
					this.SendPropertyChanged("IdRecenzije");
					this.OnIdRecenzijeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TekstRecenzije", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TekstRecenzije
		{
			get
			{
				return this._TekstRecenzije;
			}
			set
			{
				if ((this._TekstRecenzije != value))
				{
					this.OnTekstRecenzijeChanging(value);
					this.SendPropertyChanging();
					this._TekstRecenzije = value;
					this.SendPropertyChanged("TekstRecenzije");
					this.OnTekstRecenzijeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ocena", DbType="Int NOT NULL")]
		public int Ocena
		{
			get
			{
				return this._Ocena;
			}
			set
			{
				if ((this._Ocena != value))
				{
					this.OnOcenaChanging(value);
					this.SendPropertyChanging();
					this._Ocena = value;
					this.SendPropertyChanged("Ocena");
					this.OnOcenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumRecenzije", DbType="Date NOT NULL")]
		public System.DateTime DatumRecenzije
		{
			get
			{
				return this._DatumRecenzije;
			}
			set
			{
				if ((this._DatumRecenzije != value))
				{
					this.OnDatumRecenzijeChanging(value);
					this.SendPropertyChanging();
					this._DatumRecenzije = value;
					this.SendPropertyChanged("DatumRecenzije");
					this.OnDatumRecenzijeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFilm", DbType="Int NOT NULL")]
		public int IdFilm
		{
			get
			{
				return this._IdFilm;
			}
			set
			{
				if ((this._IdFilm != value))
				{
					if (this._Film.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdFilmChanging(value);
					this.SendPropertyChanging();
					this._IdFilm = value;
					this.SendPropertyChanged("IdFilm");
					this.OnIdFilmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Film_Recenzija", Storage="_Film", ThisKey="IdFilm", OtherKey="IdFilm", IsForeignKey=true)]
		public Film Film
		{
			get
			{
				return this._Film.Entity;
			}
			set
			{
				Film previousValue = this._Film.Entity;
				if (((previousValue != value) 
							|| (this._Film.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Film.Entity = null;
						previousValue.Recenzijas.Remove(this);
					}
					this._Film.Entity = value;
					if ((value != null))
					{
						value.Recenzijas.Add(this);
						this._IdFilm = value.IdFilm;
					}
					else
					{
						this._IdFilm = default(int);
					}
					this.SendPropertyChanged("Film");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Status")]
	public partial class Status : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdStatus;
		
		private string _NazivStatusa;
		
		private EntitySet<Film> _Films;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdStatusChanging(int value);
    partial void OnIdStatusChanged();
    partial void OnNazivStatusaChanging(string value);
    partial void OnNazivStatusaChanged();
    #endregion
		
		public Status()
		{
			this._Films = new EntitySet<Film>(new Action<Film>(this.attach_Films), new Action<Film>(this.detach_Films));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdStatus", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdStatus
		{
			get
			{
				return this._IdStatus;
			}
			set
			{
				if ((this._IdStatus != value))
				{
					this.OnIdStatusChanging(value);
					this.SendPropertyChanging();
					this._IdStatus = value;
					this.SendPropertyChanged("IdStatus");
					this.OnIdStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivStatusa", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NazivStatusa
		{
			get
			{
				return this._NazivStatusa;
			}
			set
			{
				if ((this._NazivStatusa != value))
				{
					this.OnNazivStatusaChanging(value);
					this.SendPropertyChanging();
					this._NazivStatusa = value;
					this.SendPropertyChanged("NazivStatusa");
					this.OnNazivStatusaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Status_Film", Storage="_Films", ThisKey="IdStatus", OtherKey="IdStatus")]
		public EntitySet<Film> Films
		{
			get
			{
				return this._Films;
			}
			set
			{
				this._Films.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Films(Film entity)
		{
			this.SendPropertyChanging();
			entity.Status = this;
		}
		
		private void detach_Films(Film entity)
		{
			this.SendPropertyChanging();
			entity.Status = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zanr")]
	public partial class Zanr : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdZanr;
		
		private string _NazivZanra;
		
		private EntitySet<Film> _Films;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdZanrChanging(int value);
    partial void OnIdZanrChanged();
    partial void OnNazivZanraChanging(string value);
    partial void OnNazivZanraChanged();
    #endregion
		
		public Zanr()
		{
			this._Films = new EntitySet<Film>(new Action<Film>(this.attach_Films), new Action<Film>(this.detach_Films));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdZanr", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdZanr
		{
			get
			{
				return this._IdZanr;
			}
			set
			{
				if ((this._IdZanr != value))
				{
					this.OnIdZanrChanging(value);
					this.SendPropertyChanging();
					this._IdZanr = value;
					this.SendPropertyChanged("IdZanr");
					this.OnIdZanrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivZanra", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NazivZanra
		{
			get
			{
				return this._NazivZanra;
			}
			set
			{
				if ((this._NazivZanra != value))
				{
					this.OnNazivZanraChanging(value);
					this.SendPropertyChanging();
					this._NazivZanra = value;
					this.SendPropertyChanged("NazivZanra");
					this.OnNazivZanraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Zanr_Film", Storage="_Films", ThisKey="IdZanr", OtherKey="IdZanr")]
		public EntitySet<Film> Films
		{
			get
			{
				return this._Films;
			}
			set
			{
				this._Films.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Films(Film entity)
		{
			this.SendPropertyChanging();
			entity.Zanr = this;
		}
		
		private void detach_Films(Film entity)
		{
			this.SendPropertyChanging();
			entity.Zanr = null;
		}
	}
}
#pragma warning restore 1591
