//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFProjekat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FilmoviDBEntities : DbContext
    {
        public FilmoviDBEntities()
    : base("FilmoviDBEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<Recenzija> Recenzijas { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Zanr> Zanrs { get; set; }
    
        public virtual int sp_DodajFilm(string naziv, Nullable<System.DateTime> datumGledanja, Nullable<int> idZanr, Nullable<int> idStatus)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var datumGledanjaParameter = datumGledanja.HasValue ?
                new ObjectParameter("DatumGledanja", datumGledanja) :
                new ObjectParameter("DatumGledanja", typeof(System.DateTime));
    
            var idZanrParameter = idZanr.HasValue ?
                new ObjectParameter("IdZanr", idZanr) :
                new ObjectParameter("IdZanr", typeof(int));
    
            var idStatusParameter = idStatus.HasValue ?
                new ObjectParameter("IdStatus", idStatus) :
                new ObjectParameter("IdStatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DodajFilm", nazivParameter, datumGledanjaParameter, idZanrParameter, idStatusParameter);
        }
    
        public virtual int sp_DodajRecenziju(string tekstRecenzije, Nullable<int> ocena, Nullable<System.DateTime> datumRecenzije, Nullable<int> idFilm)
        {
            var tekstRecenzijeParameter = tekstRecenzije != null ?
                new ObjectParameter("TekstRecenzije", tekstRecenzije) :
                new ObjectParameter("TekstRecenzije", typeof(string));
    
            var ocenaParameter = ocena.HasValue ?
                new ObjectParameter("Ocena", ocena) :
                new ObjectParameter("Ocena", typeof(int));
    
            var datumRecenzijeParameter = datumRecenzije.HasValue ?
                new ObjectParameter("DatumRecenzije", datumRecenzije) :
                new ObjectParameter("DatumRecenzije", typeof(System.DateTime));
    
            var idFilmParameter = idFilm.HasValue ?
                new ObjectParameter("IdFilm", idFilm) :
                new ObjectParameter("IdFilm", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DodajRecenziju", tekstRecenzijeParameter, ocenaParameter, datumRecenzijeParameter, idFilmParameter);
        }
    
        public virtual int sp_DodajZanr(string nazivZanra)
        {
            var nazivZanraParameter = nazivZanra != null ?
                new ObjectParameter("NazivZanra", nazivZanra) :
                new ObjectParameter("NazivZanra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DodajZanr", nazivZanraParameter);
        }
    }
}
