//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFProjekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Recenzijas = new HashSet<Recenzija>();
        }
    
        public int IdFilm { get; set; }
        public string Naziv { get; set; }
        public System.DateTime DatumGledanja { get; set; }
        public int IdZanr { get; set; }
        public int IdStatus { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Zanr Zanr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recenzija> Recenzijas { get; set; }
    }
}
