//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFProjekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recenzija
    {
        public int IdRecenzije { get; set; }
        public string TekstRecenzije { get; set; }
        public int Ocena { get; set; }
        public System.DateTime DatumRecenzije { get; set; }
        public int IdFilm { get; set; }
    
        public virtual Film Film { get; set; }
    }
}
